name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Step 4: Build and start the Docker Compose app
    - name: Build and run Docker Compose
      run: |
        docker-compose up --build -d

    # Step 5: Run tests
    - name: Test the application
      run: |
        curl --retry 5 --retry-delay 10 --fail http://localhost:8080 || exit 1

    # Step 6: Shut down Docker Compose
    - name: Shut down Docker Compose
      run: docker-compose down
