services:
  openobserve:
    image: openobserve/openobserve:latest
    container_name: openobserve
    ports:
      - "5080:5080"
      - "8080:8080"
    environment:
      # NEU: E-Mail + Passwort im RFC-5322-Format
      - ZO_ROOT_USER_EMAIL=admin@mydomain.local
      - ZO_ROOT_USER_PASSWORD=secret
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=activity_tracker_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  activity_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:5000"
    volumes:
      - ./templates:/app/templates
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    command: flask run --host=0.0.0.0
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://user:password@db:5432/activity_tracker_db
      - FLASK_ENV=development
      - FLASK_DEBUG=1

      # OpenObserve-Umgebungsvariablen
      - OPENOBSERVE_USERNAME=admin@mydomain.local
      - OPENOBSERVE_PASSWORD=secret
      - OPENOBSERVE_URL=http://openobserve:5080/api/default/_json
    depends_on:
      - db
      - openobserve

volumes:
  db_data: