services:
  openobserve:
      image: openobserve/openobserve:latest
      container_name: openobserve
      ports:
        - "5080:5080"
        - "8080:8080"
      environment:
        - ZO_ROOT_USER_EMAIL=admin@mydomain.local
        - ZO_ROOT_USER_PASSWORD=secret

  activity_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:5000"
    environment:
      # Enable Flask debug mode
      - FLASK_DEBUG=1
      # OpenObserve-Umgebungsvariablen
      - OPENOBSERVE_USERNAME=admin@mydomain.local
      - OPENOBSERVE_PASSWORD=secret
      - OPENOBSERVE_URL=http://openobserve:5080/api/default/testStream/_json
    env_file:
      - "env.docker"
    depends_on:
      - db
      - openobserve

  db:
    image: postgres:17
    container_name: db
    shm_size: 128mb
    environment:
      POSTGRES_DB: activity_tracker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_secret
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgres_secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d activity_tracker_db"]
      interval: 10s
      retries: 5

volumes:
  db_data:
secrets:
  postgres_secret:
    file: ./postgres_password.txt