services:
  activity_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:5000"
    volumes:
      - ./templates:/app/templates
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    command: flask run --host=0.0.0.0
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/activity_tracker_db
    depends_on:
      - db
  db:
    build:
      context: ./database  # Directory containing the database Dockerfile
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: activity_tracker_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Optional: Expose port if needed for debugging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: