version: '3.9'

services:
  activity_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:5000"
    volumes:
      - ./templates:/app/templates
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    command: flask run --host=0.0.0.0
