services:
  openobserve:
      image: openobserve/openobserve:latest
      container_name: openobserve
      ports:
        - "5080:5080"
        - "8080:8080"
      env_file:
        - "openobserve_env.docker"

  activity_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:5000"
    environment:
      # Enable Flask debug mode to enable logging
      - FLASK_DEBUG=1
    env_file:
      - "app_env.docker"
    depends_on:
      - db
      - openobserve

  db:
    image: postgres:17
    container_name: db
    shm_size: 128mb
    environment:
      POSTGRES_DB: activity_tracker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_secret
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgres_secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d activity_tracker_db"]
      interval: 10s
      retries: 5

volumes:
  db_data:
secrets:
  postgres_secret:
    file: ./postgres_password.txt