services:
  activity_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:5000"
    env_file:
      - "env.docker"
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: db
    shm_size: 128mb
    environment:
      POSTGRES_DB: activity_tracker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_secret
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - postgres_secret

volumes:
  db_data:
secrets:
  postgres_secret:
    file: ./postgres_password.txt