name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2'

    - name: Build and run Docker Compose
      run: |
        docker-compose up --build -d

    - name: Test the application
      run: |
        echo "Waiting for the app to start..."
        sleep 20
        curl --retry 5 --retry-delay 10 --fail http://localhost:9000 || exit 1

    - name: Shut down Docker Compose
      run: docker-compose down